// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CMB.UI.Common
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    [UIFrame.UIAttributes.UIPackageIDAttribute("xfj22cqc", "Common")]
    [UIFrame.UIAttributes.UIPackageItemIDAttribute("gdpz1", typeof(Button1))]
    public partial class Button1 : FairyGUI.GButton
    {
        
        const string URL = "ui://xfj22cqcgdpz1";
        
        private FairyGUI.GComponent _gObject;
        
        private FairyGUI.GGraph m_n0;
        
        private FairyGUI.GGraph m_n1;
        
        private FairyGUI.GGraph m_n2;
        
        static Button1()
        {
            FairyGUI.UIObjectFactory.SetPackageItemExtension(Button1.URL, typeof(Button1));
        }
        
        public Button1()
        {
        }
        
        public Button1(FairyGUI.GComponent gObject)
        {
            this._gObject = gObject;
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n0_gdpz")]
        public virtual FairyGUI.GGraph N0
        {
            get
            {
                if (object.Equals(this.m_n0, null))
                {
                    this.m_n0 = ((FairyGUI.GGraph)(this.GetChildById("n0_gdpz")));
                }
                return this.m_n0;
            }
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n1_gdpz")]
        public virtual FairyGUI.GGraph N1
        {
            get
            {
                if (object.Equals(this.m_n1, null))
                {
                    this.m_n1 = ((FairyGUI.GGraph)(this.GetChildById("n1_gdpz")));
                }
                return this.m_n1;
            }
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n2_gdpz")]
        public virtual FairyGUI.GGraph N2
        {
            get
            {
                if (object.Equals(this.m_n2, null))
                {
                    this.m_n2 = ((FairyGUI.GGraph)(this.GetChildById("n2_gdpz")));
                }
                return this.m_n2;
            }
        }
        
        public static void CreateInstanceAsync(FairyGUI.UIPackage.CreateObjectCallback cb)
        {
            FairyGUI.UIPackage.CreateObjectAsync("Common", "Button1", cb);
        }
        
        public static Button1 CreateInstance()
        {
            return ((Button1)(FairyGUI.UIPackage.CreateObject("Common", "Button1")));
        }
    }
    
    public class Button1_rx : UIFrame.IRxComponent
    {
        
        private UIFrame.UIBase _uiBase;
        
        private Button1 _handle;
        
        public Button1_rx(UIFrame.UIBase _uiBase, Button1 _handle)
        {
            this._uiBase = _uiBase;
            this._handle = _handle;
        }
        
        public virtual UIFrame.UIBase UiBase
        {
            get
            {
                return this._uiBase;
            }
        }
        
        public virtual FairyGUI.GObject GObject
        {
            get
            {
                return this._handle;
            }
        }
        
        public virtual UIFrame.GGraphSub N0
        {
            get
            {
                UIFrame.GGraphSub n0_rx;
                n0_rx = new UIFrame.GGraphSub(this._uiBase, this._handle.N0);
                return n0_rx;
            }
        }
        
        public virtual UIFrame.GGraphSub N1
        {
            get
            {
                UIFrame.GGraphSub n1_rx;
                n1_rx = new UIFrame.GGraphSub(this._uiBase, this._handle.N1);
                return n1_rx;
            }
        }
        
        public virtual UIFrame.GGraphSub N2
        {
            get
            {
                UIFrame.GGraphSub n2_rx;
                n2_rx = new UIFrame.GGraphSub(this._uiBase, this._handle.N2);
                return n2_rx;
            }
        }
    }
    
    public class Button1_databind
    {
    }
}
