// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CMB.UI.Common
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    [UIFrame.UIAttributes.UIPackageIDAttribute("xfj22cqc", "Common")]
    [UIFrame.UIAttributes.UIPackageItemIDAttribute("gdpz0", typeof(Component1))]
    public partial class Component1 : FairyGUI.GComponent
    {
        
        const string URL = "ui://xfj22cqcgdpz0";
        
        private FairyGUI.GComponent _gObject;
        
        private FairyGUI.GGraph m_n0;
        
        private FairyGUI.GGraph m_n1;
        
        private CMB.UI.Common.Button1 m_n2;
        
        private Component2 m_n3;
        
        static Component1()
        {
            FairyGUI.UIObjectFactory.SetPackageItemExtension(Component1.URL, typeof(Component1));
        }
        
        public Component1()
        {
        }
        
        public Component1(FairyGUI.GComponent gObject)
        {
            this._gObject = gObject;
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n0_gdpz")]
        public virtual FairyGUI.GGraph N0
        {
            get
            {
                if (object.Equals(this.m_n0, null))
                {
                    this.m_n0 = ((FairyGUI.GGraph)(this.GetChildById("n0_gdpz")));
                }
                return this.m_n0;
            }
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n1_gdpz")]
        public virtual FairyGUI.GGraph N1
        {
            get
            {
                if (object.Equals(this.m_n1, null))
                {
                    this.m_n1 = ((FairyGUI.GGraph)(this.GetChildById("n1_gdpz")));
                }
                return this.m_n1;
            }
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n2_xq7i")]
        public virtual CMB.UI.Common.Button1 N2
        {
            get
            {
                if (object.Equals(this.m_n2, null))
                {
                    this.m_n2 = ((CMB.UI.Common.Button1)(this.GetChildById("n2_xq7i")));
                }
                return this.m_n2;
            }
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n3_xq7i")]
        public virtual Component2 N3
        {
            get
            {
                if (object.Equals(this.m_n3, null))
                {
                    this.m_n3 = ((Component2)(this.GetChildById("n3_xq7i")));
                }
                return this.m_n3;
            }
        }
        
        public static void CreateInstanceAsync(FairyGUI.UIPackage.CreateObjectCallback cb)
        {
            FairyGUI.UIPackage.CreateObjectAsync("Common", "Component1", cb);
        }
        
        public static Component1 CreateInstance()
        {
            return ((Component1)(FairyGUI.UIPackage.CreateObject("Common", "Component1")));
        }
    }
    
    public class Component1_rx : UIFrame.IRxComponent
    {
        
        private UIFrame.UIBase _uiBase;
        
        private Component1 _handle;
        
        public Component1_rx(UIFrame.UIBase _uiBase, Component1 _handle)
        {
            this._uiBase = _uiBase;
            this._handle = _handle;
        }
        
        public virtual UIFrame.UIBase UiBase
        {
            get
            {
                return this._uiBase;
            }
        }
        
        public virtual FairyGUI.GObject GObject
        {
            get
            {
                return this._handle;
            }
        }
        
        public virtual UIFrame.GGraphSub N0
        {
            get
            {
                UIFrame.GGraphSub n0_rx;
                n0_rx = new UIFrame.GGraphSub(this._uiBase, this._handle.N0);
                return n0_rx;
            }
        }
        
        public virtual UIFrame.GGraphSub N1
        {
            get
            {
                UIFrame.GGraphSub n1_rx;
                n1_rx = new UIFrame.GGraphSub(this._uiBase, this._handle.N1);
                return n1_rx;
            }
        }
        
        public virtual UIFrame.GButtonSub N2
        {
            get
            {
                UIFrame.GButtonSub n2_rx;
                n2_rx = new UIFrame.GButtonSub(this._uiBase, this._handle.N2);
                return n2_rx;
            }
        }
        
        public virtual UIFrame.GComponentSub N3
        {
            get
            {
                UIFrame.GComponentSub n3_rx;
                n3_rx = new UIFrame.GComponentSub(this._uiBase, this._handle.N3);
                return n3_rx;
            }
        }
        
        public virtual Component2_rx N3_typed
        {
            get
            {
                return new Component2_rx(this._uiBase, this._handle.N3);
            }
        }
    }
    
    public class Component1_databind
    {
    }
}
