// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CMB.UI.Common
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    [UIFrame.UIAttributes.UIPackageIDAttribute("xfj22cqc", "Common")]
    [UIFrame.UIAttributes.UIPackageItemIDAttribute("xq7i2", typeof(Component2))]
    public partial class Component2 : FairyGUI.GComponent
    {
        
        const string URL = "ui://xfj22cqcxq7i2";
        
        private FairyGUI.GComponent _gObject;
        
        private FairyGUI.GTextField m_n0;
        
        private FairyGUI.GGraph m_n1;
        
        static Component2()
        {
            FairyGUI.UIObjectFactory.SetPackageItemExtension(Component2.URL, typeof(Component2));
        }
        
        public Component2()
        {
        }
        
        public Component2(FairyGUI.GComponent gObject)
        {
            this._gObject = gObject;
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n0_xq7i")]
        public virtual FairyGUI.GTextField N0
        {
            get
            {
                if (object.Equals(this.m_n0, null))
                {
                    this.m_n0 = ((FairyGUI.GTextField)(this.GetChildById("n0_xq7i")));
                }
                return this.m_n0;
            }
        }
        
        [UIFrame.UIAttributes.UIDisplayItemIDAttribute("ID:n1_xq7i")]
        public virtual FairyGUI.GGraph N1
        {
            get
            {
                if (object.Equals(this.m_n1, null))
                {
                    this.m_n1 = ((FairyGUI.GGraph)(this.GetChildById("n1_xq7i")));
                }
                return this.m_n1;
            }
        }
        
        public static void CreateInstanceAsync(FairyGUI.UIPackage.CreateObjectCallback cb)
        {
            FairyGUI.UIPackage.CreateObjectAsync("Common", "Component2", cb);
        }
        
        public static Component2 CreateInstance()
        {
            return ((Component2)(FairyGUI.UIPackage.CreateObject("Common", "Component2")));
        }
    }
    
    public class Component2_rx : UIFrame.IRxComponent
    {
        
        private UIFrame.UIBase _uiBase;
        
        private Component2 _handle;
        
        public Component2_rx(UIFrame.UIBase _uiBase, Component2 _handle)
        {
            this._uiBase = _uiBase;
            this._handle = _handle;
        }
        
        public virtual UIFrame.UIBase UiBase
        {
            get
            {
                return this._uiBase;
            }
        }
        
        public virtual FairyGUI.GObject GObject
        {
            get
            {
                return this._handle;
            }
        }
        
        public virtual UIFrame.GTextFieldSub N0
        {
            get
            {
                UIFrame.GTextFieldSub n0_rx;
                n0_rx = new UIFrame.GTextFieldSub(this._uiBase, this._handle.N0);
                return n0_rx;
            }
        }
        
        public virtual UIFrame.GGraphSub N1
        {
            get
            {
                UIFrame.GGraphSub n1_rx;
                n1_rx = new UIFrame.GGraphSub(this._uiBase, this._handle.N1);
                return n1_rx;
            }
        }
    }
    
    public class Component2_databind
    {
    }
}
